name: PrefixPlus
main: me.luras.prefixplus.Main
version: 1.2
authors: [MrCoolKhaled]
loadbefore: [Essentials]
commands:
  prefix:
    description: Shows help page
    usage: /<command>
  setprefix:
    description: Adds a prefix to the player
  setnamecolor:
    description: Changes the NameColor of a player
permissions:
    prefixplus.prefix:
        description: Shows help page
        default: op
    prefixplus.setprefix:
        description: Adds a prefix to the player
        default: op
    prefixplus.reload:
        description: Reloads the config
        default: op
    prefixplus.setnamecolor:
        description: Changes the NameColor of a player
        default: op